"""initial

Revision ID: 554da17d53b0
Revises:
Create Date: 2026-07-22 17:05:37.068509

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "554da17d53b0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
